---
exclude_paths:
  - "node_modules/**"
  - "admin/**"
  - "specs/**"
  - "cypress/**"
  - "__tests__" # should we check test scripts? i'm ignoring them for now just for minimal output -Euvin
  - "**/*.css"