# Takes care of documentation generation when a new feature is
# successfully merged with the codebase

name: generate-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  doc-generation-job:
    # For automatic documentation generation
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Run JSDoc
      uses: andstor/jsdoc-action@v1.2.0