# Takes care of documentation generation when a new feature is
# successfully merged with the codebase

name: generate-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  doc-generation-job:
    # For automatic documentation generation
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Run JSDoc
      uses: andstor/jsdoc-action@v1.2.0
      with:
        source_dir: ./source
        recurse: true
        output_dir: ./docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
