# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # TESTING
    - run: npm test

    # CODE QUALITY
    - name: Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@4.0.0

    # LINTER
    - run: eslint .

    # FORMATTER
    - name: Prettier Action
      uses: creyD/prettier_action@v4.0
      with:
        dry: True # won't overwrite files automatically, just warns us
        prettier_options: "--check" # recommended to use with dry, outputs analysis results
        only_changed: True # i think this only runs prettier on changed code
        # in the future if we plan to do only matching custom file patterns then we'd need to forgo only_changed